services:
  - type: web
    name: roblox-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
